use_frameworks!

platform :ios, '11.0'

target 'CategoryToolSwift_Example' do
  pod 'CategoryToolSwift', :path => '../'

  target 'CategoryToolSwift_Tests' do
    inherit! :search_paths

    
  end
end
